In [ ]:
import pandas as pd

#Upload the CSV file and read it into a DataFrame
from google.colab import files
uploaded = files.upload()

# Assuming the file name is 'movies.csv'
df = pd.read_csv('glass_reviews - glass_reviews.csv')

Saving glass_reviews - glass_reviews.csv to glass_reviews - glass_reviews (3).csv

In [ ]:

# Inspect the first few rows of the DataFrame
print("First five rows of the dataset:")
print(df.head())

# Get a summary of the DataFrame
print("\nDataFrame summary:")
print(df.info())

First five rows of the dataset:
   review_id               rating_date  count_helpful  count_unhelpful  \
0          1  2025-06-03T00:00:00.000Z              0                0
1          2  2025-05-29T00:00:00.000Z              0                0
2          3  2025-05-28T00:00:00.000Z              0                0
3          4  2025-05-26T00:00:00.000Z              0                0
4          5  2025-05-23T00:00:00.000Z              0                0

   employee_length employee_status                       employee_type  \
0              0.0         REGULAR                    Current employee
1              1.0        CONTRACT  Current employee, less than 1 year
2              1.0         REGULAR  Current employee, less than 1 year
3              2.0       PART_TIME                   Current employees
4              0.0         REGULAR                    Current employee

   flag_covid  flag_featured flags_business_outlook  ... review_advice  \
0       False          False                    NaN  ...           NaN
1       False          False               POSITIVE  ...           NaN
2       False          False               POSITIVE  ...           NaN
3       False          False               POSITIVE  ...           NaN
4       False          False                    NaN  ...           NaN

  career_opportunities_rating  employee_location  \
0                         NaN       Richmond, VA
1                         NaN       Brampton, ON
2                         NaN         Bolton, ON
3                         NaN     Swedesboro, NJ
4                         NaN         Whitby, ON

                employee_job_title  \
0  Warehouse Fulfillment Associate
1              Warehouse Associate
2              Warehouse Associate
3                         Employee
4            Fulfillment Associate

                         advice_to_management  \
0                          don’t micro manage
1  Remove all attitude manager from warehouse
2                                         NaN
3                                         NaN
4                                         NaN

                                         review_pros  \
0  not interactive \ncan leave or take off whenev...
1                      good and easy work enviorment
2                          help to grow , good pay ,
3                    Plenty of work\nMeet new people
4  Good Holiday pay \nAdditional benefits for per...

                                         review_cons  \
0      inhumane \ndraining physically &amp; mentally
1  Sticks rules and completing targets any how, o...
2  limited opportunities for advancement,No clear...
3                 Tough on the body\nLabor intensive
4            Not hiring permanent employees directly

  rating_compensation_benefits  rating_senior_leadership  \
0                          0.0                       0.0
1                          5.0                       3.0
2                          5.0                       5.0
3                          2.0                       2.0
4                          0.0                       0.0

   rating_career_opportunities
0                          0.0
1                          5.0
2                          5.0
3                          3.0
4                          0.0

[5 rows x 28 columns]

DataFrame summary:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 28 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   review_id                     140 non-null    int64
 1   rating_date                   140 non-null    object
 2   count_helpful                 140 non-null    int64
 3   count_unhelpful               140 non-null    int64
 4   employee_length               129 non-null    float64
 5   employee_status               138 non-null    object
 6   employee_type                 138 non-null    object
 7   flag_covid                    140 non-null    bool
 8   flag_featured                 140 non-null    bool
 9   flags_business_outlook        68 non-null     object
 10  flags_ceo_approval            69 non-null     object
 11  flags_recommend_frend         78 non-null     object
 12  rating_culture_values         136 non-null    float64
 13  rating_diversity_inclusion    137 non-null    float64
 14  rating_overall                140 non-null    int64
 15  rating_work_life              137 non-null    float64
 16  summary                       139 non-null    object
 17  company_name                  140 non-null    object
 18  review_advice                 0 non-null      float64
 19  career_opportunities_rating   0 non-null      float64
 20  employee_location             129 non-null    object
 21  employee_job_title            135 non-null    object
 22  advice_to_management          42 non-null     object
 23  review_pros                   140 non-null    object
 24  review_cons                   140 non-null    object
 25  rating_compensation_benefits  138 non-null    float64
 26  rating_senior_leadership      137 non-null    float64
 27  rating_career_opportunities   138 non-null    float64
dtypes: bool(2), float64(9), int64(4), object(13)
memory usage: 28.8+ KB
None

In [ ]:
df['company_name'].value_counts()

company_name
Amazon Fulfillment Center    140
Name: count, dtype: int64

In [ ]:
# Check how many values are missing in each column
df.isnull().sum().sort_values(ascending=False)

# See how many unique values each column has
df.nunique().sort_values()

review_advice                     0
career_opportunities_rating       0
count_unhelpful                   1
count_helpful                     1
flag_covid                        1
company_name                      1
flag_featured                     1
flags_recommend_frend             2
flags_ceo_approval                3
flags_business_outlook            3
rating_overall                    5
employee_status                   5
rating_work_life                  6
rating_culture_values             6
rating_diversity_inclusion        6
employee_type                     6
rating_senior_leadership          6
rating_career_opportunities       6
rating_compensation_benefits      6
employee_length                   9
advice_to_management             42
employee_job_title               68
rating_date                      99
employee_location               100
summary                         130
review_pros                     139
review_cons                     139
review_id                       140
dtype: int64

In [ ]:
df = df.drop(columns=['company_name', 'review_advice', 'career_opportunities_rating'])
df.head()

,review_id,rating_date,count_helpful,count_unhelpful,employee_length,employee_status,employee_type,flag_covid,flag_featured,flags_business_outlook,...,rating_work_life,summary,employee_location,employee_job_title,advice_to_management,review_pros,review_cons,rating_compensation_benefits,rating_senior_leadership,rating_career_opportunities
0,1,2025-06-03T00:00:00.000Z,0,0,0.0,REGULAR,Current employee,False,False,NaN,...,0.0,Amazon,"Richmond, VA",Warehouse Fulfillment Associate,don’t micro manage,not interactive \ncan leave or take off whenev...,inhumane \ndraining physically &amp; mentally,0.0,0.0,0.0
1,2,2025-05-29T00:00:00.000Z,0,0,1.0,CONTRACT,"Current employee, less than 1 year",False,False,POSITIVE,...,3.0,Good,"Brampton, ON",Warehouse Associate,Remove all attitude manager from warehouse,good and easy work enviorment,"Sticks rules and completing targets any how, o...",5.0,3.0,5.0
2,3,2025-05-28T00:00:00.000Z,0,0,1.0,REGULAR,"Current employee, less than 1 year",False,False,POSITIVE,...,5.0,Good experience,"Bolton, ON",Warehouse Associate,NaN,"help to grow , good pay ,","limited opportunities for advancement,No clear...",5.0,5.0,5.0
3,4,2025-05-26T00:00:00.000Z,0,0,2.0,PART_TIME,Current employees,False,False,POSITIVE,...,2.0,Dhdh,"Swedesboro, NJ",Employee,NaN,Plenty of work\nMeet new people,Tough on the body\nLabor intensive,2.0,2.0,3.0
4,5,2025-05-23T00:00:00.000Z,0,0,0.0,REGULAR,Current employee,False,False,NaN,...,0.0,Good Pay rate,"Whitby, ON",Fulfillment Associate,NaN,Good Holiday pay \nAdditional benefits for per...,Not hiring permanent employees directly,0.0,0.0,0.0

In [ ]:
df.isnull().sum().sort_values(ascending=False)

advice_to_management            98
flags_business_outlook          72
flags_ceo_approval              71
flags_recommend_frend           62
employee_location               11
employee_length                 11
employee_job_title               5
rating_culture_values            4
rating_diversity_inclusion       3
rating_work_life                 3
rating_senior_leadership         3
rating_career_opportunities      2
rating_compensation_benefits     2
employee_status                  2
employee_type                    2
summary                          1
review_id                        0
flag_featured                    0
flag_covid                       0
count_helpful                    0
count_unhelpful                  0
rating_date                      0
rating_overall                   0
review_pros                      0
review_cons                      0
dtype: int64

In [ ]:
df = df.dropna(subset=['summary'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 139 entries, 0 to 139
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   review_id                     139 non-null    int64
 1   rating_date                   139 non-null    object
 2   count_helpful                 139 non-null    int64
 3   count_unhelpful               139 non-null    int64
 4   employee_length               128 non-null    float64
 5   employee_status               137 non-null    object
 6   employee_type                 137 non-null    object
 7   flag_covid                    139 non-null    bool
 8   flag_featured                 139 non-null    bool
 9   flags_business_outlook        68 non-null     object
 10  flags_ceo_approval            69 non-null     object
 11  flags_recommend_frend         77 non-null     object
 12  rating_culture_values         135 non-null    float64
 13  rating_diversity_inclusion    136 non-null    float64
 14  rating_overall                139 non-null    int64
 15  rating_work_life              136 non-null    float64
 16  summary                       139 non-null    object
 17  employee_location             128 non-null    object
 18  employee_job_title            134 non-null    object
 19  advice_to_management          42 non-null     object
 20  review_pros                   139 non-null    object
 21  review_cons                   139 non-null    object
 22  rating_compensation_benefits  137 non-null    float64
 23  rating_senior_leadership      136 non-null    float64
 24  rating_career_opportunities   137 non-null    float64
dtypes: bool(2), float64(7), int64(4), object(12)
memory usage: 26.3+ KB

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.to_csv('glassdoor_cleaned.csv', index=False)